import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script src="./node_modules/jquery/dist/jquery.min.js"></script>
        <script src="./node_modules/datatables.net/js/dataTables.min.js"></script>
      </body>
    </html>
  );
}
